# Generated by Django 5.1.1 on 2024-10-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relacion', '0002_rename_estudiantecurso_relacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('estado', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=1, max_digits=8)),
                ('relacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacion.relacion')),
            ],
            options={
                'db_table': 'Matriculas',
            },
        ),
    ]
