# Generated by Django 5.1.1 on 2024-09-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_fecha_fin_curso_fecha_inicio'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='personas', to='curso.curso'),
        ),
    ]
