# Generated by Django 5.1.1 on 2024-09-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_persona_cursos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
