# Generated by Django 5.1.1 on 2024-09-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cursos',
        ),
    ]
