# Generated by Django 5.1.1 on 2024-10-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='email',
            new_name='correo',
        ),
    ]
