# Generated by Django 5.1.1 on 2024-10-14 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_curso_descripcion_remove_curso_fecha_fin_and_more'),
        ('persona', '0005_rename_apellidos_persona_apellido_and_more'),
        ('relacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstudianteCurso',
            new_name='Relacion',
        ),
    ]
