# Generated by Django 5.1.1 on 2024-09-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
