# Generated by Django 5.1.1 on 2024-09-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_fecha_fin_curso_fecha_inicio'),
        ('persona', '0002_persona_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horas',
        ),
        migrations.AddField(
            model_name='curso',
            name='capacidadMaxima',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
    ]
